# Generated by Django 4.2.4 on 2023-08-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('rector', 'Ректор'), ('secretary', 'Секретарша'), ('client', 'Клиент')], max_length=256, verbose_name='Роль'),
        ),
    ]
