# Generated by Django 4.2.4 on 2023-08-08 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('rector', 'Ректор'), ('pro_rector', 'Проректор')], max_length=256, verbose_name='Роль')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание запроса')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appeals', to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
