# Generated by Django 4.2.4 on 2023-08-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание'), ('come_in', 'Заходите'), ('reject', 'Отказ')], default='waiting', max_length=256, verbose_name='Статус'),
        ),
    ]
